version: '3'
services:
  natureauthors-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: natureauthors-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "5000:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: natureauthors.ucsd.edu
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: natureauthors.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu


networks:
  nginx-net:
    external:
      name: nginx-net